version: '3.7'

services:
  app:
    container_name: eaurp-app
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - .:/app:cached

  database:
    image: mysql:5.7
    container_name: eaurp-database
    ports:
      - 33061:3306
    environment:
      - "MYSQL_USER=eaurp"
      - "MYSQL_PASSWORD=Sup3rPassw0rd"
      - "MYSQL_DATABASE=eaurp_db"
      - "MYSQL_ROOT_PASSWORD=Sup3rPassword20009"
