version: '3.7'

services:
  app:
    container_name: laracon-app
    build:
      context: .
    ports:
      - 1234:80
    volumes:
      - .:/app:cached

  database:
    image: mysql:5.7
    container_name: laracon-database
    ports:
      - 33061:3306
    environment:
      - "MYSQL_USER=eaurp"
      - "MYSQL_PASSWORD=Sup3rPassword^152@"
      - "MYSQL_DATABASE=eaurp_db"
      - "MYSQL_ROOT_PASSWORD=@Sup3rPassword@20009"
